name: skipgo_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  logger: ^2.4.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  

dev_dependencies:
  build_runner: ^2.4.11 
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  lints: ^4.0.0
  test: ^1.24.0
